<?php
/**
 *-------------------------------------------------------------------------p*
 * 操作日志
 *-------------------------------------------------------------------------h*
 * @copyright  Copyright (c) 2015-2021 Phcent Inc. (http://www.phcent.com)
 *-------------------------------------------------------------------------c*
 * @license    http://www.phcent.com        p h c e n t . c o m
 *-------------------------------------------------------------------------e*
 * @link       http://www.phcent.com
 *-------------------------------------------------------------------------n*
 * @since      象讯·PHP 知识付费问答系统
 *-------------------------------------------------------------------------t*
 */


namespace Phcent\WebmanAsk\Controllers\Admin\V0;


use Phcent\WebmanAsk\Logic\AdminControllerLogic;
use support\Request;

class LogController extends AdminControllerLogic
{
    public  $model = \Phcent\WebmanAsk\Model\AdminLog::class;
    public  $name = '操作日志';
    public  $projectName = '系统管理-操作日志管理-';
    public function create(Request $request)
    {
        return []; // TODO: Change the autogenerated stub
    }
    public function update(Request $request, $id)
    {
        return []; // TODO: Change the autogenerated stub
    }
}