<?php
/**
 *-------------------------------------------------------------------------p*
 *
 *-------------------------------------------------------------------------h*
 * @copyright  Copyright (c) 2015-2021 Phcent Inc. (http://www.phcent.com)
 *-------------------------------------------------------------------------c*
 * @license    http://www.phcent.com        p h c e n t . c o m
 *-------------------------------------------------------------------------e*
 * @link       http://www.phcent.com
 *-------------------------------------------------------------------------n*
 * @since      象讯·PHP 知识付费问答系统
 *-------------------------------------------------------------------------t*
 */


namespace Phcent\WebmanAsk\Controllers\Admin\V0;


use Phcent\WebmanAsk\Logic\AdminControllerLogic;

use Respect\Validation\Validator;

class MenuController extends AdminControllerLogic
{
    public  $model = \Phcent\WebmanAsk\Model\SysMenu::class;
    public  $name = '菜单';
    public  $projectName = '系统管理-菜单管理-';
    public $orderBy = ['id'=>'asc'];

    public function getAdminCreate()
    {
        $data['menuList'] = (new $this->model)->get();
        return $data; // TODO: Change the autogenerated stub
    }
    public function beforeAdminCreate($user)
    {
        $params =  phcentParams([
            'name',
            'path',
            'pid' => 0,
            'controller',
            'icon',
            'status'
        ]);
        return $params; // TODO: Change the autogenerated stub
    }
    public function insertGetAdminUpdate($info, $id)
    {
        $data['info'] = $info;
        $data['menuList'] = (new $this->model)->get();
        return $data;  // TODO: Change the autogenerated stub
    }
    public function beforeAdminUpdate($user, $id)
    {
        Validator::input(\request()->all(), [
            'name' => Validator::length(1, 32)->noWhitespace()->setName('菜单名称'),
        ]);
        $params = phcentParams([
            'name',
            'path',
            'pid' =>0,
            'controller',
            'icon',
            'status'
        ]);
        return $params;
    }

}