<?php
/**
 *-------------------------------------------------------------------------p*
 *
 *-------------------------------------------------------------------------h*
 * @copyright  Copyright (c) 2015-2021 Phcent Inc. (http://www.phcent.com)
 *-------------------------------------------------------------------------c*
 * @license    http://www.phcent.com        p h c e n t . c o m
 *-------------------------------------------------------------------------e*
 * @link       http://www.phcent.com
 *-------------------------------------------------------------------------n*
 * @since      象讯·PHP 知识付费问答系统
 *-------------------------------------------------------------------------t*
 */


namespace Phcent\WebmanAsk\Controllers\Admin\V0;


use Phcent\WebmanAsk\Logic\AdminControllerLogic;

use Phcent\WebmanAsk\Model\SysMenu;
use Phcent\WebmanAsk\Model\SysTeamMenu;
use Phcent\WebmanAsk\Service\UserService;
use Respect\Validation\Validator;
use support\Db;

class TeamController extends AdminControllerLogic
{
    public  $model = \Phcent\WebmanAsk\Model\SysTeam::class;
    public  $name = '权限组';
    public  $projectName = '系统管理-权限组管理-';
    public function getAdminCreate()
    {
        $data['menuList'] = SysMenu::where('status',1)->select('id','name','status','pid')->get();
        return $data; // TODO: Change the autogenerated stub
    }
    public function beforeAdminCreate($user)
    {
        Validator::input(\request()->all(), [
            'name' => Validator::length(1, 32)->noWhitespace()->setName('权限组名称'),
            'role' => Validator::arrayType()->setName('关联菜单'),
        ]);
        $params = phcentParams([
            'name'
        ]);
        return $params;
    }
    public function insertAdminCreate($user, $create)
    {
        foreach (request()->input('role') as $val){
            SysTeamMenu::create([
                'team_id' => $create->id,
                'menu_id' => $val['menu_id'],
                'perm' => $val['perm']
            ]);
        }
    }

    public function insertGetAdminUpdate($info, $id)
    {
        $data['menuList'] = SysMenu::where('status',1)->select('id','name','status','pid')->get();
        $data['teamList'] = SysTeamMenu::where('team_id',$id)->get();
        $data['info'] = $info;
        return $data;
    }
    public function beforeAdminUpdate($user, $id)
    {
        Validator::input(\request()->all(), [
            'name' => Validator::length(1, 32)->noWhitespace()->setName('权限组名称'),
            'role' => Validator::arrayType()->setName('关联菜单'),
        ]);
        $params = phcentParams([
            'name'
        ]);
        return $params;
    }
    public function insertAdminUpdate($user, $params, $info, $id)
    {
        SysTeamMenu::where('team_id',$id)->delete();
        foreach (request()->input('role') as $val){
            SysTeamMenu::create([
                'team_id' => $id,
                'menu_id' => $val['menu_id'],
                'perm' => $val['perm']
            ]);
        }
    }

    public function adminDestroy($user,$ids,$id){
        if(!is_numeric($id) || empty($id)){
            throw new \Exception('编号错误');
        }
        if(intval($id) === 1){
            throw new \Exception('默认管理员组别不能删除');
        }
        (new $this->model)->destroy($id);
        SysTeamMenu::where('team_id',$id)->delete();
        return [];
    }


}