<?php
/**
 *-------------------------------------------------------------------------p*
 *
 *-------------------------------------------------------------------------h*
 * @copyright  Copyright (c) 2015-2021 Phcent Inc. (http://www.phcent.com)
 *-------------------------------------------------------------------------c*
 * @license    http://www.phcent.com        p h c e n t . c o m
 *-------------------------------------------------------------------------e*
 * @link       http://www.phcent.com
 *-------------------------------------------------------------------------n*
 * @since      象讯·PHP 知识付费问答系统
 *-------------------------------------------------------------------------t*
 */


namespace Phcent\WebmanAsk\Controllers\Admin\V0;


use Phcent\WebmanAsk\Logic\AdminControllerLogic;
use Phcent\WebmanAsk\Model\AdminTeam;

use Respect\Validation\Validator;

class UserController extends AdminControllerLogic
{
    public  $model = \Phcent\WebmanAsk\Model\User::class;
    public  $name = '会员';
    public  $projectName = '系统管理-会员管理-';

    public function getAdminCreate()
    {
        $data['teamList'] = AdminTeam::get();
        return $data; // TODO: Change the autogenerated stub
    }

    public function beforeAdminCreate($user)
    {
        Validator::input(\request()->all(), [
            'name' => Validator::length(1, 32)->noWhitespace()->setName('用户名'),
            'nick_name' => Validator::length(1, 32)->noWhitespace()->setName('昵称'),
            'password' => Validator::length(6, 64)->noWhitespace()->setName('密码'),
            'current_team_id' => Validator::digit()->in([1,2])->setName('组别'),
        ]);
        $params = phcentParams([
            'name',
            'email',
            'mobile',
            'password',
            'current_team_id',
            'avatar',
            'status',
            'nick_name'
        ]);
        return $params; // TODO: Change the autogenerated stub
    }

    /**
     * @param $user
     * @param $id
     * @return array|mixed
     */
    public function beforeAdminUpdate($user, $id)
    {
        Validator::input(\request()->all(), [
            'name' => Validator::length(1, 32)->noWhitespace()->setName('用户名'),
            'nick_name' => Validator::length(1, 32)->noWhitespace()->setName('昵称'),
            'password' => Validator::length(6, 64)->noWhitespace()->setName('密码')
        ]);
        $params = phcentParams([
            'name',
            'email',
            'mobile',
            'password',
            'current_team_id',
            'avatar',
            'status',
            'nick_name'
        ]);
        return $params;
    }

}