<?php
/**
 *-------------------------------------------------------------------------p*
 *
 *-------------------------------------------------------------------------h*
 * @copyright  Copyright (c) 2015-2021 Phcent Inc. (http://www.phcent.com)
 *-------------------------------------------------------------------------c*
 * @license    http://www.phcent.com        p h c e n t . c o m
 *-------------------------------------------------------------------------e*
 * @link       http://www.phcent.com
 *-------------------------------------------------------------------------n*
 * @since      象讯·PHP知识付费问答系统
 *-------------------------------------------------------------------------t*
 */


namespace Phcent\WebmanAsk\Controllers\Admin\System;


use Phcent\WebmanAsk\Logic\AdminControllerLogic;
use support\Request;

class OrdersController extends AdminControllerLogic
{
    public  $model = \Phcent\WebmanAsk\Model\SysOrders::class;
    public  $name = '订单';
    public  $projectName = '系统管理-订单管理-';

    public function update(Request $request, $id)
    {
        return []; // TODO: Change the autogenerated stub
    }

    public function create(Request $request)
    {
        return [];
    }

    public function destroy(Request $request, $id)
    {
        return [];
    }

    /**
     * 设置收到款项
     * @param Request $request
     * @param $id
     */
    public function pay(Request $request, $id)
    {

    }

}