<?php
/**
 *-------------------------------------------------------------------------p*
 * 问答分类
 *-------------------------------------------------------------------------h*
 * @copyright  Copyright (c) 2015-2021 Phcent Inc. (http://www.phcent.com)
 *-------------------------------------------------------------------------c*
 * @license    http://www.phcent.com        p h c e n t . c o m
 *-------------------------------------------------------------------------e*
 * @link       http://www.phcent.com
 *-------------------------------------------------------------------------n*
 * @since      象讯·PHP 知识付费问答系统
 *-------------------------------------------------------------------------t*
 */


namespace Phcent\WebmanAsk\Controllers\Admin\Ask;


use Phcent\WebmanAsk\Logic\AdminControllerLogic;

use Phcent\WebmanAsk\Service\CategoryService;
use Phcent\WebmanAsk\Service\ConfigService;
use Respect\Validation\Validator;

class CategoryController extends AdminControllerLogic
{
    public  $model = \Phcent\WebmanAsk\Model\AskCategory::class;
    public  $name = '分类';
    public  $projectName = '问答管理-分类管理-';

    public function afterAdminIndex($list)
    {
        $data['list'] = $list->items();
        $data['categoryType'] = ConfigService::getKeyName([1,2,5,6],config('phcentask.allType'));
        return $data;
    }
    public function getAdminCreate()
    {
        $data['categoryType'] = ConfigService::getKeyName([1,2,5,6],config('phcentask.allType'));
        return $data; // TODO: Change the autogenerated stub
    }
    public function beforeAdminCreate($user)
    {
        Validator::input(\request()->all(), [
            'name' => Validator::length(1, 32)->noWhitespace()->setName('分类名称'),
            'sort' => Validator::digit()->min(0)->setName('权重'),
            'type' => Validator::digit()->in([1,2,5,6])->setName('所属'),
            'status' => Validator::digit()->in([1,0])->setName('状态'),
        ]);
        $params = phcentParams([
            'name',
            'icon',
            'sort' => 0,
            'summary',
            'seo_title',
            'seo_keyword',
            'seo_description',
            'color',
            'type' => 1,
            'status' => 1
        ]);
        return $params;
    }
    public function afterAdminUpdate($user, $update)
    {
        //清除缓存
        CategoryService::delCache();
        $data['info'] = $update;
        return $data;
    }
    public function insertGetAdminUpdate($info, $id)
    {
        $data['categoryType'] = ConfigService::getKeyName([1,2,5,6],config('phcentask.allType'));
        $data['info'] = $info;
        return $data; // TODO: Change the autogenerated stub
    }
    public function beforeAdminUpdate($user, $id)
    {
        Validator::input(\request()->all(), [
            'name' => Validator::length(1, 32)->noWhitespace()->setName('分类名称'),
            'sort' => Validator::digit()->min(0)->setName('权重'),
            'type' => Validator::digit()->in([1,2,5,6])->setName('所属'),
            'status' => Validator::digit()->in([1,0])->setName('状态'),
        ]);
        $params = phcentParams([
            'summary',
            'seo_title',
            'seo_keyword',
            'seo_description',
            'name',
            'icon',
            'sort',
            'type',
            'status',
            'color'
        ]);
        return $params;
    }
    public function afterAdminCreate($user, $create)
    {
        //清除缓存
        CategoryService::delCache();
        $data['info'] = $create;
        return $data;
    }
    public function adminDestroy($user, $ids, $id)
    {
        parent::adminDestroy($user, $ids, $id); // TODO: Change the autogenerated stub
        CategoryService::delCache();
    }
}