<?php
/**
 *-------------------------------------------------------------------------p*
 *
 *-------------------------------------------------------------------------h*
 * @copyright  Copyright (c) 2015-2021 Phcent Inc. (http://www.phcent.com)
 *-------------------------------------------------------------------------c*
 * @license    http://www.phcent.com        p h c e n t . c o m
 *-------------------------------------------------------------------------e*
 * @link       http://www.phcent.com
 *-------------------------------------------------------------------------n*
 * @since      象讯·PHP 知识付费问答系统
 *-------------------------------------------------------------------------t*
 */


namespace Phcent\WebmanAsk\Controllers\Admin\Ask;


use Phcent\WebmanAsk\Logic\AdminControllerLogic;
use Respect\Validation\Validator;

class GradeController extends AdminControllerLogic
{
    public  $model = \Phcent\WebmanAsk\Model\AskGrade::class;
    public  $name = '会员等级';
    public  $projectName = '问答管理-会员等级管理';

    public function beforeAdminCreate($user)
    {
        Validator::input(\request()->all(), [
            'name' => Validator::length(1, 32)->noWhitespace()->setName('等级名称'),
            'points' => Validator::digit()->min(0)->setName('所需积分'),
        ]);
        $params = phcentParams([
            'name',
            'image_name',
            'points'
        ]);
        return $params; // TODO: Change the autogenerated stub
    }
    public function beforeAdminUpdate($user, $id)
    {
        Validator::input(\request()->all(), [
            'name' => Validator::length(1, 32)->noWhitespace()->setName('等级名称'),
            'points' => Validator::digit()->min(0)->setName('所需积分'),
        ]);
        $params = phcentParams([
            'name',
            'image_name',
            'points'
        ]);
        return $params;
    }
}