<?php
/**
 *-------------------------------------------------------------------------p*
 *
 *-------------------------------------------------------------------------h*
 * @copyright  Copyright (c) 2015-2021 Phcent Inc. (http://www.phcent.com)
 *-------------------------------------------------------------------------c*
 * @license    http://www.phcent.com        p h c e n t . c o m
 *-------------------------------------------------------------------------e*
 * @link       http://www.phcent.com
 *-------------------------------------------------------------------------n*
 * @since      象讯·PHP 知识付费问答系统
 *-------------------------------------------------------------------------t*
 */


namespace Phcent\WebmanAsk\Controllers\Admin\V1;


use Phcent\WebmanAsk\Logic\AdminControllerLogic;
use Phcent\WebmanAsk\Logic\AskCommentLogic;
use Phcent\WebmanAsk\Model\AskReply;
use support\Request;

class AnswerController extends AdminControllerLogic
{
    public  $model = \Phcent\WebmanAsk\Model\AskAnswer::class;
    public  $name = '回答';
    public  $projectName = '问答管理-回答管理';

    /**
     * 新增数据 支持get,post类型
     * @param Request $request
     * @return \support\Response
     */
    public function create(Request $request)
    {
        return phcentError();
    }
    public function beforeAdminUpdate($user, $id)
    {
        $params = phcentParams([
            'reward_balance',
            'reward_points',
            'content',
            'digg_num',
            'step_num',
            'pay_num',
            'share_num',
            'report_num',
            'collection_num',
            'thank_num',
            'reply_num',
            'reward_time',
            'user_id',
            'status'
        ]); //允许修改字段
        return $params; // TODO: Change the autogenerated stub
    }

    public function adminDestroy($user, $ids, $id)
    {
        //删除回答
        $askComment = (new $this->model)->whereIn('id', $ids)->get();
        (new $this->model)->destroy($askComment->pluck('id'));
        //删除评论
        $askCommentReply = AskReply::whereIn('theme_id', $askComment->pluck('id'))->where('type', 1)->get();
        AskReply::destroy($askCommentReply->pluck('id'));
    }

    public function adminRecoveryDelete($user, $ids, $id)
    {
        foreach ($ids as $value) {
            AskCommentLogic::deleteAnswer($value);
        }
    }

}