<?php
/**
 *-------------------------------------------------------------------------p*
 * 会员动态
 *-------------------------------------------------------------------------h*
 * @copyright  Copyright (c) 2015-2021 Phcent Inc. (http://www.phcent.com)
 *-------------------------------------------------------------------------c*
 * @license    http://www.phcent.com        p h c e n t . c o m
 *-------------------------------------------------------------------------e*
 * @link       http://www.phcent.com
 *-------------------------------------------------------------------------n*
 * @since      象讯·PHP 知识付费问答系统
 *-------------------------------------------------------------------------t*
 */


namespace Phcent\WebmanAsk\Controllers\Admin\V1;

use Phcent\WebmanAsk\Logic\AdminControllerLogic;

use Respect\Validation\Validator;
use support\Request;

class DynamicController extends AdminControllerLogic
{
    public  $model = \Phcent\WebmanAsk\Model\AskDynamic::class;
    public  $name = '动态';
    public  $projectName = '问答管理-动态管理';

    /**
     * 新增
     * @param Request $request
     * @return \support\Response
     * @throws \Throwable
     */
    public function create(Request $request)
    {

    }
    public function insertGetAdminUpdate($info, $id)
    {
        $data['info'] = $info;
        $data['dynamicType'] = config('phcentask.dynamicType');
        return $data; // TODO: Change the autogenerated stub
    }
    public function beforeAdminUpdate($user, $id)
    {
        Validator::input(\request()->all(), [
            'type' => Validator::digit()->in([1,2,3,4])->setName('所属'),
        ]);
        $params = phcentParams([
            'type',
            'theme_id',
            'operation_stage',
            'title',
            'content'
        ]);
    }
}