<?php
/**
 *-------------------------------------------------------------------------p*
 * 会员私信管理
 *-------------------------------------------------------------------------h*
 * @copyright  Copyright (c) 2015-2021 Phcent Inc. (http://www.phcent.com)
 *-------------------------------------------------------------------------c*
 * @license    http://www.phcent.com        p h c e n t . c o m
 *-------------------------------------------------------------------------e*
 * @link       http://www.phcent.com
 *-------------------------------------------------------------------------n*
 * @since      象讯·PHP 知识付费问答系统
 *-------------------------------------------------------------------------t*
 */


namespace Phcent\WebmanAsk\Controllers\Admin\V1;


use Phcent\WebmanAsk\Logic\AdminControllerLogic;

use support\Request;

class MessageController extends AdminControllerLogic
{
    public  $model = \Phcent\WebmanAsk\Model\AskMessage::class;
    public  $name = '私信';
    public  $projectName = '问答管理-私信管理';

    /**
     * 新增
     * @param Request $request
     * @return \support\Response
     * @throws \Throwable
     */
    public function create(Request $request)
    {

    }
    public function beforeAdminUpdate($user, $id)
    {
        $params = phcentParams([
            'user_id',
            'user_name',
            'to_user_id',
            'to_user_name',
            'content',
            'is_read',
            'user_del',
            'to_user_del'
        ]);
        return $params; // TODO: Change the autogenerated stub
    }
}