<?php
/**
 *-------------------------------------------------------------------------p*
 * 问答评论
 *-------------------------------------------------------------------------h*
 * @copyright  Copyright (c) 2015-2021 Phcent Inc. (http://www.phcent.com)
 *-------------------------------------------------------------------------c*
 * @license    http://www.phcent.com        p h c e n t . c o m
 *-------------------------------------------------------------------------e*
 * @link       http://www.phcent.com
 *-------------------------------------------------------------------------n*
 * @since      象讯·PHP商城系统Pro
 *-------------------------------------------------------------------------t*
 */


namespace Phcent\WebmanAsk\Controllers\Admin\V1;

use Phcent\WebmanAsk\Logic\AdminControllerLogic;
use support\Request;

class ReplyController extends AdminControllerLogic
{
    public  $model = \Phcent\WebmanAsk\Model\AskReply::class;
    public  $name = '评论';
    public  $projectName = '问答管理-评论管理-';

    public function create(Request $request)
    {
        return []; // TODO: Change the autogenerated stub
    }

}