<?php
/**
 *-------------------------------------------------------------------------p*
 * 举报管理
 *-------------------------------------------------------------------------h*
 * @copyright  Copyright (c) 2015-2021 Phcent Inc. (http://www.phcent.com)
 *-------------------------------------------------------------------------c*
 * @license    http://www.phcent.com        p h c e n t . c o m
 *-------------------------------------------------------------------------e*
 * @link       http://www.phcent.com
 *-------------------------------------------------------------------------n*
 * @since      象讯·PHP 知识付费问答系统
 *-------------------------------------------------------------------------t*
 */


namespace Phcent\WebmanAsk\Controllers\Admin\V1;

use Phcent\WebmanAsk\Logic\AdminControllerLogic;
use support\Request;

class ReportController extends AdminControllerLogic
{
    public  $model = \Phcent\WebmanAsk\Model\AskReport::class;
    public  $name = '举报';
    public  $projectName = '问答管理-举报管理-';

    public function afterAdminIndex($list)
    {
        $data['list'] = $list->items();
        $data['reasonList'] = config('phcentask.reasonList');
        $data['reportType'] = config('phcentask.reportType');
        return $data;
    }

    /**
     * 新增
     * @param Request $request
     * @return \support\Response
     * @throws \Throwable
     */
    public function create(Request $request)
    {

    }
    public function insertGetAdminUpdate($info, $id)
    {
        $data['reasonList'] = config('phcentask.reasonList');
        $data['reportType'] = config('phcentask.reportType');
        $data['info'] = $info;
        return $data; // TODO: Change the autogenerated stub
    }
    public function beforeAdminUpdate($user, $id)
    {
        $params = phcentParams([
            'reason',
            'status',
            'theme_id',
            'type',
            'content',
            'ip',
            'user_agent',
            'user_id'
        ]);
        return $params; // TODO: Change the autogenerated stub
    }
}