<?php
/**
 *-------------------------------------------------------------------------p*
 * 签到日志
 *-------------------------------------------------------------------------h*
 * @copyright  Copyright (c) 2015-2021 Phcent Inc. (http://www.phcent.com)
 *-------------------------------------------------------------------------c*
 * @license    http://www.phcent.com        p h c e n t . c o m
 *-------------------------------------------------------------------------e*
 * @link       http://www.phcent.com
 *-------------------------------------------------------------------------n*
 * @since      象讯·PHP 知识付费问答系统
 *-------------------------------------------------------------------------t*
 */


namespace Phcent\WebmanAsk\Controllers\Admin\V1;


use Phcent\WebmanAsk\Logic\AdminControllerLogic;

use support\Request;

class SigninController extends AdminControllerLogic
{
    public  $model = \Phcent\WebmanAsk\Model\AskSigninLog::class;
    public  $name = '签到日志';
    public  $projectName = '问答管理-签到日志管理-';

    public function create(Request $request)
    {
        return []; // TODO: Change the autogenerated stub
    }
    public function update(Request $request, $id)
    {
        return []; // TODO: Change the autogenerated stub
    }
    public function destroy(Request $request, $id)
    {
        return []; // TODO: Change the autogenerated stub
    }
}