<?php
/**
 *-------------------------------------------------------------------------p*
 * 问答话题模块
 *-------------------------------------------------------------------------h*
 * @copyright  Copyright (c) 2015-2021 Phcent Inc. (http://www.phcent.com)
 *-------------------------------------------------------------------------c*
 * @license    http://www.phcent.com        p h c e n t . c o m
 *-------------------------------------------------------------------------e*
 * @link       http://www.phcent.com
 *-------------------------------------------------------------------------n*
 * @since      象讯·PHP 知识付费问答系统
 *-------------------------------------------------------------------------t*
 */


namespace Phcent\WebmanAsk\Controllers\Admin\V1;

use Phcent\WebmanAsk\Logic\AdminControllerLogic;
use Phcent\WebmanAsk\Model\AskCategory;
use Respect\Validation\Validator;

class TagsController extends AdminControllerLogic
{
    public  $model = \Phcent\WebmanAsk\Model\AskTags::class;
    public  $name = '话题';
    public  $projectName = '问答管理-话题管理-';

    public function getAdminCreate()
    {
        $data['category'] = AskCategory::where('type',3)->get();
        return $data; // TODO: Change the autogenerated stub
    }
    public function beforeAdminCreate($user)
    {
        Validator::input(\request()->all(), [
            'name' => Validator::length(1, 32)->noWhitespace()->setName('标签名称'),
            'status' => Validator::digit()->in([1,2])->setName('状态'),
        ]);
        $params = phcentParams([
            'name' => '',
            'icon',
            'image',
            'keyword',
            'description',
            'question_num' => 0,
            'article_num' => 0,
            'follow_num' => 0,
            'report_num' =>0,
            'hot_sort' => 0,
            'status' => 1
        ]);
        return $params;
    }
    public function insertGetAdminUpdate($info, $id)
    {
        $data['info'] = $info;
        $data['category'] = AskCategory::where('type',3)->get();
        return $data; // TODO: Change the autogenerated stub
    }
    public function beforeAdminUpdate($user, $id)
    {
        $params = phcentParams([
            'name',
            'icon',
            'image',
            'keyword',
            'description',
            'question_num',
            'article_num',
            'follow_num',
            'report_num',
            'hot_sort',
            'status'
        ]); //允许修改字段
        return $params; // TODO: Change the autogenerated stub
    }

}